version: '3'

services:

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached
      - /dev/bus/usb:/dev/bus/usb

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    privileged: true
